const IMFeedActionsConstants = {
  SET_MAIN_FEED_POSTS: 'SET_MAIN_FEED_POSTS',
  SET_MAIN_FEED_POST_REACTIONS: 'SET_MAIN_FEED_POST_REACTIONS',
  SET_DISCOVER_FEED_POSTS: 'SET_DISCOVER_FEED_POSTS',
  SET_CURRENT_USER_FEED_POSTS: 'SET_CURRENT_USER_FEED_POSTS',
  SET_MAIN_STORIES: 'SET_MAIN_STORIES',
  DID_SUBSCRIBE: 'DID_SUBSCRIBE_TO_MAIN_FEED',
};

export default IMFeedActionsConstants;
