language: node_js
node_js:
  - 'stable'
env:
  global:
    - TWILIO_ACCOUNT_SID=AC00fe742eba2bc869e7aa23de1029ef60
    - TWILIO_API_KEY=SK5c263dc292f2c58257702f0108b2780c
    - TWILIO_API_SECRET=jyR3fWurAGCEbPVfAlelQQiTh3EJ1fpP
